<h1> Mostrar las diferentes librerias para aplicar algoritmos de aprendizaje automático </h1>

In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [1]:
#Craer datos de simulación.
from sklearn.datasets import make_regression
features, target, coefficients = make_regression(n_samples = 100,
    n_features = 3,
    n_informative = 3,
    n_targets = 1,
    noise = 0.0,
    coef = True,
    random_state = 1)
print('Matriz \n', features[:3])
print('Vector \n', target[:3])

Matriz 
 [[ 1.29322588 -0.61736206 -0.11044703]
 [-2.793085    0.36633201  1.93752881]
 [ 0.80186103 -0.18656977  0.0465673 ]]
Vector 
 [-10.37865986  25.5124503   19.67705609]


In [33]:
#Dividir los datos para entrenamiento y prueba.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(features, target, random_state=42)

#Escojer un módelo
from sklearn.linear_model import LinearRegression

#Entrenar el módelo.
modelo = LinearRegression().fit(X_train, y_train)

print("Coeficientes: {}".format(modelo.coef_))
print("Intecepto: {}".format(modelo.intercept_))

print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Coeficientes: [44.19042807 98.97517077 58.15774073]
Intecepto: 1.0658141036401503e-14
Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00


<h1>Evaluemos otros modelos </h1>

In [34]:
from sklearn.linear_model import Ridge
modelo = Ridge().fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00


In [35]:
modelo = Ridge(alpha=10).fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 0.98
Porcentaje de acierto pruebas: 0.98


In [36]:
modelo = Ridge(alpha=0.1).fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00


In [37]:
from sklearn.linear_model import Lasso
modelo = Lasso().fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))
print("Número de varibles utilizadas: {}".format(np.sum(modelo.coef_ != 0)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00
Número de varibles utilizadas: 3


In [38]:
# we increase the default setting of "max_iter",
# otherwise the model would warn us that we should increase max_iter.
modelo = Lasso(alpha=0.01, max_iter=100000).fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))
print("Número de varibles utilizadas: {}".format(np.sum(modelo.coef_ != 0)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00
Número de varibles utilizadas: 3


In [39]:
modelo = Lasso(alpha=0.0001, max_iter=100000).fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))
print("Número de varibles utilizadas: {}".format(np.sum(modelo.coef_ != 0)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00
Número de varibles utilizadas: 3


In [40]:
from sklearn.tree import DecisionTreeRegressor
modelo = DecisionTreeRegressor().fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 0.60


In [41]:
from sklearn.svm import SVR
modelo = SVR().fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 0.09
Porcentaje de acierto pruebas: 0.08


In [44]:
from sklearn import linear_model
modelo = linear_model.BayesianRidge().fit(X_train, y_train)
print("Porcentaje de acierto entrenamiento: {:.2f}".format(modelo.score(X_train, y_train)))
print("Porcentaje de acierto pruebas: {:.2f}".format(modelo.score(X_test, y_test)))

Porcentaje de acierto entrenamiento: 1.00
Porcentaje de acierto pruebas: 1.00
